### PR TITLE
to check or test please

### PR DESCRIPTION
**Pull request by sergiomb2**

### CODE REVIEW

**Comment by madebr** [comment]
Status update:
I'm still refactoring the hell outta this program. Not finished yet.
Most of these commits will not apply cleanly to the new tree.

Just keep this PR open until things have settled.

**Comment by sergiomb2** [comment]
OK, good to hear you and the plan , the plan  also looks good , I will keep my commits rebased .
Thanks for the feedback

**Comment by madebr** [comment]
I've just pushed a first iteration of the refactoring. Only the first tab uses a new backend.
Can you test? Please open new issues when finding problems.

**Comment by sergiomb2** [comment]
filter by languages stops to work

**Comment by sergiomb2** [comment]
search also stops to work .. 
```
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/searchNameWidget.py", line 102, in onButtonSearchByTitle
    movies = s.search_movie(search_text, 'all')
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/FileManagement/search.py", line 83, in search_movie
    search = self.parse_results(xml_page.read())
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/FileManagement/search.py", line 380, in parse_results
    temp_movie = Movie(sub)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/FileManagement/search.py", line 41, in __init__
    self.MovieYear = str(movieInfo['MovieYear'])
KeyError: 'MovieYear'
```

**Comment by madebr** [comment]
Hey,
First of, thanks for testing.
- The filter by languages does indeed not work, because I haven't implemented it yet,
- I cannot reproduce your search by name. What was your query? (I tried not to touch the code of the second tab. Yet.)
Please open an issue for these problems :)

**Comment by sergiomb2** [comment]
please merge some of these commits , now all the 8 patches just have a 119 lines !

**Comment by sergiomb2** [comment]
Hello , Nice work !, I had update my pull request, now I just have 4 commits 
First is a trivial to .gitignore, second small script : pip3 install -U langdetect pymediainfo --user
3rd one python fix for python <= 3.5 I guess  
4th bump the version !!, yeh (now just in one place )

**Comment by madebr** [comment]
Again, thanks for testing!

These patches are useful for me to know what issue(s) you might be having using the app.
They will be integrated in the project one way or another.

**Comment by sergiomb2** [comment]
Hello, the "Fix pathlib issue" commit is trying fix when I run 
```
scripts/gui/generate.py -C
scripts/gui/generate.py 
```

I hadn't time yet to check https://github.com/madebr/subdownloader/issues/25 properly , just had time to rebase my patches ... , I will give you feedback soon as I test it . 

Thanks and cheers .

**Comment by madebr** [comment]
Seems like I created a dependency on Python 3.6.
Python 3.6 added support for os.PathLike objects to open.

**Comment by madebr** [comment]
[argcomplate](https://pypi.python.org/pypi/argcomplete) is an optional package. It is not required.

**Comment by sergiomb2** [comment]
> argcomplate is an optional package. It is not required.

but langdetect is needed

**Comment by sergiomb2** [comment]
./subdownloader.py -V /run/media/sergio/F9CE-11CD/series/
Traceback (most recent call last):
  File "./subdownloader.py", line 5, in <module>
    from subdownloader.client.__main__ import main
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/__main__.py", line 10, in <module>
    from subdownloader.client.configuration import configuration_init
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/configuration.py", line 11, in <module>
    from subdownloader.languages.language import Language, UnknownLanguage
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/languages/language.py", line 7, in <module>
    import langdetect
ModuleNotFoundError: No module named 'langdetect'

the prove that  langdetect is needed

**Comment by madebr** [comment]
You were correct about the hard `langdetect` dependency. Did not know that it was still there. `langdetect` should be optional now.

**Comment by sergiomb2** [comment]
BTW 
I started build python-pymediainfo packages [1] ( I'm not sure that is the final name for the package) , I inspired on opensuse package [2] 
[1]
https://copr.fedorainfracloud.org/coprs/sergiomb/builds_for_Stable_Releases/build/676459/
[2]
https://pkgs.org/download/pymediainfo

**Comment by madebr** [comment]
Hey @sergiomb2,

- The `.gitignore` in the root already ignores `.pyc` files, so the `__pycache__` is unnecessary
- I don't think a script to install the dependencies in the `script` folder is the correct way. `setup.py` should install the dependencies.
- The version is already bumped to `2.1.0`
- I included your `README.md` patch, slightly modified.

**Comment by sergiomb2** [comment]
Cool Thanks , I checked Readme.md and it is great , only left the addition of script, the intention of the script is remind me how I install the python modules that I don't have in distro ... 

BTW surprise [1] pymediainfo is in official fedora repos !

[1] https://src.fedoraproject.org/rpms/python-pymediainfo/blob/master/f/python-pymediainfo.spec

**Comment by madebr** [comment]
Nice work.
Will `langdetect` be packaged for fedora as well? That would solve your troubles.
Can you also look into creating a `subdownloader-nautilus` package?

**Comment by sergiomb2** [comment]
> Can you also look into creating a subdownloader-nautilus package?

no problem in creating a sub package nautilus.   
Please note pymediainfo is in official repos but I wasn't involved at most the person was inspired in my package on corp , which btw was inspired on one opensuse package

**Pull request closed without merging**
